### ISSUE TITLE
Add a check for certain un-needed env values 

### ISSUE THREAD

**Issue by LakshayaT** [OsmosysSoftware/osmo-notify#44]
In the current implementation, we need to specify SMTP and/or Mailgun even if we are not using one of them. The service not being used should not require its env config values either, and not cause any errors.

This is caused due to `getOrThrow` being used. 

Possible resolution can be to replace `getOrThrow` with other method (like `get`) or add a condition check for such values.

**Comment by osm-vishnukyatannawar** [comment]
Is this issue still open? @LakshayaT

**Comment by LakshayaT** [comment]
The fix for this issue was in development, the code for which can be found here: https://github.com/LakshayaT/osmo-notify/tree/fix-env-validations

However, before giving a PR for this fix, some more extensive testing is required so as to avoid any unexpected issues.

**Comment by xixas** [comment]
Issue is fixed in this PR: https://github.com/OsmosysSoftware/osmo-notify/pull/55
