### ISSUE TITLE
Use TypeORM type value from .env file

### ISSUE THREAD

**Issue by LakshayaT** [OsmosysSoftware/osmo-notify#5]
### Issue Description

When trying to set the TypeORM configuration value `type` through value from `.env`, the following error is reported:

![image](https://github.com/OsmosysSoftware/osmo-notify/assets/108812833/7ed561b4-c580-46e0-b09c-c0c99f7f8393)

Affected code:

```ts
import { Injectable } from '@nestjs/common';
import { TypeOrmModuleOptions, TypeOrmOptionsFactory } from '@nestjs/typeorm';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class DatabaseConfiguration implements TypeOrmOptionsFactory {
  constructor(private configService: ConfigService) {}

  createTypeOrmOptions(): TypeOrmModuleOptions {
    return {
      type: this.configService.get<string>('DB_TYPE'),
      host: this.configService.get<string>('DB_HOST'),
      port: +this.configService.get<number>('DB_PORT'),
      username: this.configService.get<string>('DB_USERNAME'),
      password: this.configService.get<string>('DB_PASSWORD'),
      database: this.configService.get<string>('DB_NAME'),
      entities: [__dirname + '/**/*.entity{.ts,.js}'],
      synchronize: false,
    };
  }
}
```

The `.env` file has the needed entry:

```
DB_TYPE=mysql
```

### What I Have Tried

If switching to hardcoded value in the above, the error is no longer reported:

```
...
return {
  type: 'mysql',
  ...
```

**Comment by xixas** [comment]
Type should be for `DatabaseType` provided by typeORM. But I had to cast the whole thing as TypeOrmModuleOptions.
{
      type: this.configService.get<DatabaseType>('DB_TYPE'),
      host: this.configService.get<string>('DB_HOST'),
      port: +this.configService.get<number>('DB_PORT'),
      username: this.configService.get<string>('DB_USERNAME'),
      password: this.configService.get<string>('DB_PASSWORD'),
      database: this.configService.get<string>('DB_NAME'),
      entities: [__dirname + '/**/*.entity{.ts,.js}'],
      synchronize: false,
    } as TypeOrmModuleOptions;

**Comment by xixas** [comment]
Also, use getOrThrow instead of just get.

**Comment by LakshayaT** [comment]
I have added the type `DatabaseType` to the value for `DB_TYPE` from `.env`, and after casting return value as `TypeOrmModuleOptions`, the implementation is working.

Also used getOrThrow as suggested.

Thanks a lot for the help @xixas!
